// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdkjHZwf7Wd-T8KWpzAcJ_rBGOF74AlRY',
    appId: '1:349744385353:web:0045fc9a5e0f3d7f509e98',
    messagingSenderId: '349744385353',
    projectId: 'atrails-flutter',
    authDomain: 'atrails-flutter.firebaseapp.com',
    storageBucket: 'atrails-flutter.appspot.com',
    measurementId: 'G-VEY66WVMWE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBK9DBZkNtyKZgPO4E_enotp18sv1j1TjM',
    appId: '1:349744385353:android:a0aadf30fad8c215509e98',
    messagingSenderId: '349744385353',
    projectId: 'atrails-flutter',
    storageBucket: 'atrails-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPa8py2e55yoVYvcDGb2U9jKPfGYZFWec',
    appId: '1:349744385353:ios:8c72174ac2180ac9509e98',
    messagingSenderId: '349744385353',
    projectId: 'atrails-flutter',
    storageBucket: 'atrails-flutter.appspot.com',
    iosBundleId: 'com.example.atrails',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPa8py2e55yoVYvcDGb2U9jKPfGYZFWec',
    appId: '1:349744385353:ios:8c72174ac2180ac9509e98',
    messagingSenderId: '349744385353',
    projectId: 'atrails-flutter',
    storageBucket: 'atrails-flutter.appspot.com',
    iosBundleId: 'com.example.atrails',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdkjHZwf7Wd-T8KWpzAcJ_rBGOF74AlRY',
    appId: '1:349744385353:web:238c66be1d53eb1b509e98',
    messagingSenderId: '349744385353',
    projectId: 'atrails-flutter',
    authDomain: 'atrails-flutter.firebaseapp.com',
    storageBucket: 'atrails-flutter.appspot.com',
    measurementId: 'G-NHBFSDNE2M',
  );
}
